### ISSUE TITLE
The document fails to show the basic turoial code

### ISSUE THREAD

**Issue by Paalon** [dream-num/univer.ai#132]
The official document doesn't show the tutorial code for creating instance and registering plugins:
https://univer.ai/guides/sheet/getting-started/installation#usage
https://github.com/dream-num/univer.ai/blob/733d317111e93123b8a056fc7c804a75eaf0f458/src/pages/guides/sheet/getting-started/installation.en-US.mdx?plain=1#L80-L106
Hard to understand.

**Comment by jikkai** [comment]
Clicking here will expand detailed example code. However, we do realize that it is difficult for readers of the documentation to notice such a button, so we will make some modifications later.

<img width="869" alt="image" src="https://github.com/dream-num/univer.ai/assets/14025786/15038f4d-da46-4977-8b2a-2787a0d26b54">

**Comment by Paalon** [comment]
Oh, I haven't realized it.
