### ISSUE TITLE
Feedback for “Univer Sheet API”

### ISSUE THREAD

**Issue by Lucianing** [dream-num/univer.ai#136]
```ts
univerAPI.getSheetHooks().onCellDrop((cell) => {
  // Get the cell currently pointed to by the mouse
  console.log(cell);
})
```

`onCellDrop` api is not supported in version 0.1.11，

**Comment by Dushusir** [comment]
> ```ts
> univerAPI.getSheetHooks().onCellDrop((cell) => {
>   // Get the cell currently pointed to by the mouse
>   console.log(cell);
> })
> ```
> 
> `onCellDrop` api is not supported in version 0.1.11，

Thank you for your attention, this feature will be released in version 0.1.12
