### ISSUE TITLE
An error occurred when a hyperlink was generated

### ISSUE THREAD

**Issue by 13032648540** [dream-num/univer.ai#184]
The following error is reported when installing dependencies, importing, and using according to the official example.：
```
Cannot find "at" registered by any injector. The stack of dependencies is: "P -> at".
```

Function used: Hyperlink.
The installation steps are as follows:
1、npm install @univerjs/sheets-hyper-link-ui
2、import '@univerjs/sheets-hyper-link-ui/lib/index.css';
     import { UniverSheetsHyperLinkUIPlugin } from '@univerjs/sheets-hyper-link-ui';
3、import { LocaleType, Tools } from '@univerjs/core';
     import SheetsHyperLinkUIZhCN from '@univerjs/sheets-hyper-link-ui/locale/zh-CN';
 
    const univer = new Univer({
      theme: defaultTheme,
      locale: LocaleType.ZH_CN,
      locales: {
        [LocaleType.ZH_CN]: Tools.deepMerge(
          SheetsHyperLinkUIZhCN
        ),
      },
    });
4、univer.registerPlugin(UniverSheetsHyperLinkUIPlugin);

**Comment by jikkai** [comment]
This is the repository for the Univer documentation. We DO NOT address any issues here that are unrelated to it.
