### ISSUE TITLE
Feedback for “Sheet API”

### ISSUE THREAD

**Issue by YUandJIANG** [dream-num/univer.ai#189]
Get Range Data
Get all cell values in the range

const range = activeSheet.getRange(0, 0, 2, 2);
range.forEach((cell, row, column) => {
  console.log(cell.getValue());
});

There is a problem with this sample api
cell.getValue() This method does not exist

You can get the value via column.v

example:

const range = activeSheet.getRange(0, 0, 2, 2);
range.forEach((cell, row, column) => {
  console.log(column.v);
});

**Comment by jikkai** [comment]
Thank you for your feedback. We will confirm it later.
