### ISSUE TITLE
Question for “Installation” with Nodered with Dashboard 2.0

### ISSUE THREAD

**Issue by buschhardtt** [dream-num/univer.ai#211]
Hallo,
have someone experience or a example, how to run Univer in Nodered Dashboard 2.0? 
[https://dashboard.flowfuse.com/nodes/widgets.html](https://dashboard.flowfuse.com/nodes/widgets.html)
Its based on VueJS, maybe for experts its no problem(?)

Thank You very much
Thomas

**Comment by jikkai** [comment]
This is not the place to consult about Univer-related issues. This is just a documentation repository. If you have any questions about Univer, please submit a reproducible issue in the [Univer repository](https://github.com/dream-num/univer/issues).
