### ISSUE TITLE
Feedback for “Troubleshooting”

### ISSUE THREAD

**Issue by fbk1029** [dream-num/univer.ai#220]
![1EE3850F0529CF261AB6DB156500AC60](https://github.com/user-attachments/assets/b5d58588-458c-4641-b2b0-74855f559494)
移动端预览，表格不能拖动，选区时，会自动弹出键盘

**Comment by jikkai** [comment]
This is NOT the place to consult about Univer-related issues. It's just a documentation repository.
If you have any questions about Univer, please submit a reproduction in the [Univer](https://github.com/dream-num/univer/issues) repository.
