### ISSUE TITLE
Feedback for “Doc API”

### ISSUE THREAD

**Issue by chenxxing** [dream-num/univer.ai#227]
0.2.4版本doc默认内容以   荷塘月色\r\r作者：朱自清\r\r这  开头，文本内容无法选中，开发环境选择字体时会谈弹窗报错
![c98c92bd6c04436546e84d6468fa9ed](https://github.com/user-attachments/assets/16c8b9c9-eb6f-4278-a820-a68798dea558)
demo代码
[demo.zip](https://github.com/user-attachments/files/16556959/demo.zip)

**Comment by chenxxing** [comment]
[Uploading demo.zip…]()

**Comment by chenxxing** [comment]
[demo.zip](https://github.com/user-attachments/files/16557326/demo.zip)

**Comment by Jocs** [comment]
@chenxxing 数据有问题，paragraphs 中 startIndex 和 \r 的 index 没有对上
