### ISSUE TITLE
Feedback for “Pivot Table”

### ISSUE THREAD

**Issue by hyman928** [dream-num/univer.ai#230]
<img width="685" alt="error-pic" src="https://github.com/user-attachments/assets/b9831435-13ba-4e1d-8c3a-740e1c6d284b">

 引入了透视表插件后，会报错。

**Comment by jikkai** [comment]
This is NOT the place to consult about Univer-related issues. It's just a documentation repository.
If you have any questions about Univer, please submit a reproduction in the [Univer](https://github.com/dream-num/univer/issues) repository.
