### ISSUE TITLE
Feedback for “Di” 注册协同服务时，USIP协议下的第三方认证服务问题

### ISSUE THREAD

**Issue by fythnu** [dream-num/univer.ai#252]
你好，在注册协同服务时，服务端自动调动USIP协议第三方任务服务，但无法传递token。

    // 配置协同、打印、交换的服务端地址
    const { SNAPSHOT_SERVER_URL_KEY, COLLAB_SUBMIT_CHANGESET_URL_KEY, COLLAB_WEB_SOCKET_URL_KEY, AUTHZ_URL_KEY, SEND_CHANGESET_TIMEOUT_KEY} = UniverCollaborationClient;
    configService.setConfig(AUTHZ_URL_KEY, `http://${universerEndpoint}/universer-api/authz`);
    configService.setConfig(SNAPSHOT_SERVER_URL_KEY, `http://${universerEndpoint}/universer-api/snapshot`);
    configService.setConfig(COLLAB_SUBMIT_CHANGESET_URL_KEY, `http://${universerEndpoint}/universer-api/comb`);
    configService.setConfig(COLLAB_WEB_SOCKET_URL_KEY, `ws://${universerEndpoint}/universer-api/comb/connect`);
    configService.setConfig(SEND_CHANGESET_TIMEOUT_KEY, 200) // optional

    // 注册协同插件
    univer.registerPlugin(UniverCollaboration.UniverCollaborationPlugin);
    univer.registerPlugin(UniverCollaborationClient.UniverCollaborationClientPlugin);

**Comment by jikkai** [comment]
This is NOT the place to consult about Univer issues. It's just a documentation repository.
If you have any questions about Univer, please submit a reproduction in the [Univer](https://github.com/dream-num/univer/issues) repository.
