### ISSUE TITLE
添加【公式查看】功能

### ISSUE THREAD

**Issue by caijiamin** [dream-num/univer.ai#258]
![image](https://github.com/user-attachments/assets/5b9aa090-bbc8-423c-8f99-8d75a1663e56)

**Comment by caijiamin** [comment]
![Snipaste_2024-08-28_16-09-20](https://github.com/user-attachments/assets/1b9aa389-4e7d-4874-a013-759bc3c70221)

**Comment by jikkai** [comment]
Please do not submit feature request under the document repository.
