### ISSUE TITLE
Feedback for “Sheet API”

### ISSUE THREAD

**Issue by SakuraYou** [dream-num/univer.ai#264]
![image](https://github.com/user-attachments/assets/9caff92a-892b-469f-83c0-dbe9e74bd3ce)

实际操作：
const workbook = univerAPI.current.getActiveWorkbook();
const sheet = workbook.getActiveSheet();

"sheet" 并没有 “ insertXXX” 相关函数。
1. 看TS声明没有
![image](https://github.com/user-attachments/assets/fdfbf089-920e-4ab0-8a99-a3fd3d2cfa96)
2. 实际操作也没有
![image](https://github.com/user-attachments/assets/5a796048-62c1-441b-883c-d3cdbd87e137)

版本：0.2.9
![image](https://github.com/user-attachments/assets/bcc2160b-e51b-4538-b2a7-6faf6bbd1f63)

**Comment by hexf00** [comment]
请升级到0.2.11，后续我们也会在文档里标注该api被引入的版本号

Please upgrade to version 0.2.11. We will also indicate the version number in which the API was introduced in the documentation.

https://github.com/dream-num/univer/releases/tag/v0.2.11
