### ISSUE TITLE
Feedback for “Cell Data”

### ISSUE THREAD

**Issue by greenfire-git** [dream-num/univer.ai#283]
cell Data Type is boolean，the code example page show set 2
![图片](https://github.com/user-attachments/assets/848937a0-3a2c-4821-8d91-e0afd94a8d54)
![图片](https://github.com/user-attachments/assets/0d59deec-232a-4646-b154-75f5b509f88f)
![图片](https://github.com/user-attachments/assets/a158581d-6515-4abc-b337-0a0116825237)

**Comment by jikkai** [comment]
It seems like you might be misunderstanding how enumeration types work. Could you please double-check the documentation on https://univer.ai/typedoc/@univerjs/core/enumerations/CellValueType
