### ISSUE TITLE
按官网提示在vue3项目中引入，vscode运行后项目无表格线

### ISSUE THREAD

**Issue by ElegantV** [dream-num/univer.ai#314]
<img width="1512" alt="Snipaste_2024-09-23_10-07-31" src="https://github.com/user-attachments/assets/2e1f12fb-0fd2-44f8-9474-09fcb31b955a">
<template>
  <button @click="getSheetData()">获取数据</button>
  
  <div ref="container" class="univer-container" />
</template>

<script setup lang="ts">
import "@univerjs/sheets-ui/lib/index.css";

import "@univerjs/design/lib/index.css";
import "@univerjs/ui/lib/index.css";
import "@univerjs/docs-ui/lib/index.css";
import "@univerjs/sheets-ui/lib/index.css";
import "@univerjs/sheets-formula/lib/index.css";

import {
  Univer,
  UniverInstanceType,
  Workbook,
  LocaleType,
  Tools,
} from "@univerjs/core";
import { defaultTheme } from "@univerjs/design";
import { UniverDocsPlugin } from "@univerjs/docs";
import { UniverDocsUIPlugin } from "@univerjs/docs-ui";
import { UniverFormulaEnginePlugin } from "@univerjs/engine-formula";
import { UniverRenderEnginePlugin } from "@univerjs/engine-render";
import { UniverSheetsPlugin } from "@univerjs/sheets";
import { UniverSheetsFormulaPlugin } from "@univerjs/sheets-formula";
import { UniverSheetsUIPlugin } from "@univerjs/sheets-ui";
import { UniverUIPlugin } from "@univerjs/ui";
import { onBeforeUnmount, onMounted, ref } from "vue";
import { FUniver } from "@univerjs/facade";
// import '@univerjs/find-replace/lib/index.css';

// import { UniverFindReplacePlugin } from '@univerjs/find-replace';
// import { UniverSheetsFindReplacePlugin } from '@univerjs/sheets-find-replace';

import DesignZhCN from "@univerjs/design/locale/zh-CN";
import UIZhCN from "@univerjs/ui/locale/zh-CN";
import DocsUIZhCN from "@univerjs/docs-ui/locale/zh-CN";
import SheetsZhCN from "@univerjs/sheets/locale/zh-CN";
import SheetsUIZhCN from "@univerjs/sheets-ui/locale/zh-CN";
import SheetsFormulaZhCN from "@univerjs/sheets-formula/locale/zh-CN";

const { data } = defineProps({
  // workbook data
  data: {
    type: Object,
    default: () => ({}),
  },
});

const univerRef = ref<Univer | null>(null);
const container = ref<HTMLElement | null>(null);

onMounted(() => {
  initSheet(data);
});

const initSheet = (data = {}) => {
  const univer = new Univer({
    theme: defaultTheme,
    locale: LocaleType.ZH_CN,
    locales: {
      [LocaleType.ZH_CN]: Tools.deepMerge(
        SheetsZhCN,
        DocsUIZhCN,
        SheetsUIZhCN,
        UIZhCN,
        DesignZhCN
      ),
    },
  });
  univerRef.value = univer;

  // core plugins
  univer.registerPlugin(UniverRenderEnginePlugin);
  univer.registerPlugin(UniverFormulaEnginePlugin);
  univer.registerPlugin(UniverUIPlugin, {
    container: container.value!,
  });

  // doc plugins
  univer.registerPlugin(UniverDocsPlugin, {
    hasScroll: false,
  });
  univer.registerPlugin(UniverDocsUIPlugin);

  // sheet plugins
  univer.registerPlugin(UniverSheetsPlugin);
  univer.registerPlugin(UniverSheetsUIPlugin);
  univer.registerPlugin(UniverSheetsFormulaPlugin);

  // create workbook instance
  univer.createUnit(UniverInstanceType.UNIVER_SHEET, {});
};

const getSheetData = () => {
  const univerAPI = FUniver.newAPI(univerRef.value);
  const savedData = univerAPI.getActiveWorkbook().getSnapshot();
  console.log("savedData", savedData);
};
</script>

<style scoped>
.univer-container {
  width: 100%;
  height: 100%;
  border: 1px solid #d40d0d; /* 如果需要，可以加上一个边框 */
}
</style>

**Comment by hexf00** [comment]
看起来未正确配置 DOM 容器高度

It looks like the DOM container height is not configured correctly

**Comment by hexf00** [comment]
请勿在此仓库提交与文档无关的内容，文档问题请指出具体的页面

Please do not submit content unrelated to the document in this repository. If there is a document problem, please point out the specific page
