### ISSUE TITLE
Feedback for “Import Export” 跳转链接404

### ISSUE THREAD

**Issue by shiguoqian** [dream-num/univer.ai#330]
https://univer.ai/zh-CN/guides/sheet/facade/sheet-api#%E4%B8%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E4%BA%A4%E4%BA%92%E7%9A%84%E5%8A%9F%E8%83%BD

该链接指向页面404

**Comment by wzhudev** [comment]
Duplicate of #325.
